CREATE TABLE CLIENTS
(
  ID           NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE),
  CLIENT_CODE  VARCHAR2(5 BYTE),
  CLIENT_NAME  VARCHAR2(100 BYTE),
  NIP          VARCHAR2(10 BYTE),
  CITY         VARCHAR2(100 BYTE),
  EMAIL        VARCHAR2(100 BYTE),
  BLOCKED      NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE CLIENTS_BLOCKED_HISTORY
(
  CLIENT_CODE    VARCHAR2(5 BYTE),
  BLOCKED_AFTER  NUMBER,
  DATE_CHANGED   DATE
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ITEMS
(
  ID          NUMBER,
  ITEM_INDEX  VARCHAR2(100 BYTE),
  INDEX_NAME  VARCHAR2(200 BYTE),
  UOM         VARCHAR2(3 BYTE),
  VAT         NUMBER,
  BLOCKED     NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ORDERS
(
  ORDER_ID              NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 41 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE),
  ORDER_NAME            VARCHAR2(100 BYTE),
  CLIENT                VARCHAR2(100 BYTE),
  DATE_OF_REGISTRATION  DATE,
  DATE_TERM             DATE,
  VALUE                 FLOAT(126),
  ORDER_TYPE            VARCHAR2(5 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE ORDER_TYPES
(
  ID_TYPE    NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE),
  TYPE_CODE  VARCHAR2(5 BYTE),
  TYPE_NAME  VARCHAR2(50 BYTE)
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;


CREATE TABLE USERS
(
  USER_ID     NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 41 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP NOSCALE),
  LOGIN       VARCHAR2(200 BYTE),
  PASSWORD    VARCHAR2(200 BYTE),
  CLIENT_ADD  NUMBER,
  ITEM_ADD    NUMBER,
  ORDER_ADD   NUMBER
)
LOGGING 
NOCOMPRESS 
NO INMEMORY
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL;

/* Formatted on 06/04/2023 17:07:42 (QP5 v5.391) */
CREATE OR REPLACE TRIGGER CLIENTS_HISTORY
    AFTER UPDATE OF blocked
    ON clients
    FOR EACH ROW
BEGIN
    INSERT INTO CLIENTS_BLOCKED_HISTORY (CLIENT_CODE,
                                         BLOCKED_AFTER,
                                         DATE_CHANGED)
         VALUES (:old.client_code, :new.blocked, SYSDATE);
END;
/
